[package]
name = "ivyea-note-desktop"
version = "0.10.1"
description = "Ivyea Note 桌面端：本地 Markdown · 多端同步"
authors = ["ivyea"]
edition = "2021"

[lib]
name = "ivyea_note_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-opener = "2.5.4"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"

[profile.release]
strip = true
lto = true
codegen-units = 1
